# Adjust the run address to match the .org in the source code

basic.run:: basic.bin
	srec_cat basic.bin -binary -o basic.run

basic.bin: basic.o
	ld65 -t osic1p -vm -m basic.map -o basic.bin basic.o

basic.o: basic.asm osi_mon.asm
	ca65 -g -l basic.lst --feature labels_without_colons -o basic.o sbc_mon.asm

clean:
	$(RM) *.o *.lst *.map *.bin *.run *.mon *.c1p

distclean: clean
