#!/bin/sh
#
# Get load and run addresses from map file and output in hex in format
# to be used as arguments to the bintomon program.

L=`grep "ORG:" 2ksa-apple.lst | awk '{print $1}'`
R=`grep "^MAIN    " 2ksa-apple.map | tail -1 | awk '{print $2}'`
echo "-l 0x$L -r 0x$R"
