; Source for polled keyboard ROM. Generated by disassembling code.

LFCBE           := $FCBE
LFCC6           := $FCC6
LFCCF           := $FCCF

        *=$FD00

        txa
        pha
        tya
        pha
LFF04:  lda     #$01
LFF06:  jsr     LFCBE
        jsr     LFCC6
        bne     LFF13
LFF0E:  asl     a
        bne     LFF06
        beq     LFF66
LFF13:  lsr     a
        bcc     LFF1F
        rol     a
        cpx     #$21
        bne     LFF0E
        lda     #$1B
        bne     LFF40
LFF1F:  jsr     LFDC8
        tya
        sta     $0213
        asl     a
        asl     a
        asl     a
        sec
        sbc     $0213
        sta     $0213
        txa
        lsr     a
        jsr     LFDC8
        bne     LFF66
        clc
        tya
        adc     $0213
        tay
        lda     TABLE,y
LFF40:  cmp     $0215
        bne     LFF6B
        dec     $0214
        beq     LFF75
        ldy     #$05
LFF4C:  ldx     #$C8
LFF4E:  dex
        bne     LFF4E
        dey
        bne     LFF4C
        beq     LFF04
LFF56:  cmp     #$01
        beq     LFF8F
        ldy     #$00
        cmp     #$02
        beq     LFFA7
        ldy     #$C0
        cmp     #$20
        beq     LFFA7
LFF66:  lda     #$00
        sta     $0216
LFF6B:  sta     $0215
        lda     #$02
        sta     $0214
        bne     LFF04
LFF75:  ldx     #$96
        cmp     $0216
        bne     LFF7E
        ldx     #$14
LFF7E:  stx     $0214
        sta     $0216
        lda     #$01
        jsr     LFCBE
        jsr     LFCCF
LFF8C:  lsr     a
        bcc     LFFC2
LFF8F:  tax
        and     #$03
        beq     LFF9F
        ldy     #$10
        lda     $0215
        bpl     LFFA7
        ldy     #$F0
        bne     LFFA7
LFF9F:  ldy     #$00
        cpx     #$20
        bne     LFFA7
        ldy     #$C0
LFFA7:  lda     $0215
        and     #$7F
        cmp     #$20
        beq     LFFB7
        sty     $0213
        clc
        adc     $0213
LFFB7:  sta     $0213
        pla
        tay
        pla
        tax
        lda     $0213
        rts

LFFC2:  bne     LFF56
        ldy     #$20
        bne     LFFA7
LFDC8:  ldy     #$08
LFFCA:  dey
        asl     a
        bcc     LFFCA
        rts

TABLE:  .byte $D0, $BB, $2F, $20, $5A, $41, $51, $2C
        .byte $4D, $4E, $42, $56, $43, $58, $4B, $4A
        .byte $48, $47, $46, $44, $53, $49, $55, $59
        .byte $54, $52, $45, $57, $00, $00, $0D, $0A
        .byte $4F, $4C, $2E, $00, $FF, $2D, $BA, $30
        .byte $B9, $B8, $B7, $B6, $B5, $B4, $B3, $B2, $B1
