#!/bin/sh
#
# Get load and run addresses from map file and output in hex in format
# to be used as arguments to the bintomon program.

L=`grep "START    " a1basic.map | head -1 | awk '{ print $2 }'`
R=`grep "START    " a1basic.map | head -1 | awk '{ print $2 }'`
echo "-l 0x$L -r 0x$R"
