#!/bin/bash
#
# Send files out the serial port. Uses a suitable delay for loading
# BASIC programs on the Ohio Scientific Superboard II at 9600 bps. The
# -n option will send with no delay, which typically works when using
# the OSI Monitor program Load feature.

if [ "$#" == "0" ]
then
    echo "Usage: SEND [-n] <file...>"
    exit 1
fi

stty -F /dev/ttyUSB0 9600 -hup -clocal raw

for file in $@
do
    if [ "$file" == "-n" ]
    then
        NODELAY=1
    else
        if [ -f "$file" ]
        then
            if [ "$NODELAY" == "1" ]
            then
                ascii-xfr -s "$file" >/dev/ttyUSB0
            else
                ascii-xfr -s -l 150 -c 60 "$file" >/dev/ttyUSB0
            fi
        else
            echo "File not found: $file"
            exit 1
        fi
    fi
done
