#!/bin/sh
#
# Send a file out the serial port. Uses a suitable delay for loading
# BASIC programs on the Ohio Scientific Superboard II at 9600 bps.

if [ $# != 1 ]
then
  echo "Usage: SEND <file>"
  exit 1
fi

if [ ! -f "$1" ]
then
  echo "File not found: $1"
  exit 1
fi

stty -F /dev/ttyUSB0 9600 -hup -clocal raw
ascii-xfr -s -l 150 -c 60 $1 >/dev/ttyUSB0
