#!/bin/sh
#
# Get load and run addresses from map file and output in hex in format
# to be used as arguments to the bintomon program.

L=`grep "JMON    " jmon.map | awk '{ print $2 }' | head -1`
R=`grep "JMON    " jmon.map | awk '{ print $2 }' | head -1`
echo "-l 0x$L -r 0x$R"
